import { db } from "@/db";
import { titles, episodes, reviews } from "@/db/schema";
import { sql } from "drizzle-orm";

const V = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/";
const P = (id: number, ext = "jpeg") =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.${ext}?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200`;

type SeedTitle = typeof titles.$inferInsert & {
  eps?: { name: string; synopsis: string; duration: number }[];
};

const seedTitles: SeedTitle[] = [
  {
    slug: "endless-night",
    title: "شب بی‌پایان",
    titleEn: "Endless Night",
    type: "movie",
    year: 2024,
    rating: 8.7,
    duration: 128,
    description:
      "کارآگاه سابقی که سال‌هاست از شهر دور بوده، برای حل آخرین پرونده‌اش به تهرانِ بارانی برمی‌گردد؛ شهری که در یک شب بی‌پایان گرفتار شده و هر چراغ نئونی، رازی را پنهان می‌کند.",
    genres: ["هیجان‌انگیز", "جنایی", "نوآر"],
    poster: "/posters/endless-night.jpg",
    backdrop: P(35171253),
    videoUrl: V + "TearsOfSteel.mp4",
    director: "سامان مقدم",
    cast: ["نوید محمدزاده", "ترانه علیدوستی", "پیمان معادی"],
    ageRating: "+16",
    quality: "4K",
    featured: true,
    trendingScore: 98,
    views: 1248000,
  },
  {
    slug: "orbit-of-silence",
    title: "مدار سکوت",
    titleEn: "Orbit of Silence",
    type: "movie",
    year: 2025,
    rating: 9.1,
    duration: 142,
    description:
      "پس از قطع ارتباط با زمین، فضانورد تنهای ایستگاه «آرش» باید بین بازگشت به خانه و کشف سیگنالی ناشناخته از آن‌سوی حلقه‌های زحل، یکی را انتخاب کند.",
    genres: ["علمی‌تخیلی", "درام", "ماجراجویی"],
    poster: "/posters/orbit-of-silence.jpg",
    backdrop: P(37269529),
    videoUrl: V + "Sintel.mp4",
    director: "بهرام توکلی",
    cast: ["شهاب حسینی", "هدیه تهرانی", "بابک حمیدیان"],
    ageRating: "+13",
    quality: "4K HDR",
    featured: true,
    trendingScore: 100,
    views: 2310000,
  },
  {
    slug: "desert-winds",
    title: "بادهای کویر",
    titleEn: "Desert Winds",
    type: "movie",
    year: 2023,
    rating: 8.2,
    duration: 116,
    description:
      "زنی جوان در دل کویر لوت به دنبال کاروانی گمشده می‌گردد که پدرش ده سال پیش با آن ناپدید شد. سفری حماسی در برابر طوفان شن و گذشته‌ای که رهایش نمی‌کند.",
    genres: ["درام", "ماجراجویی", "حماسی"],
    poster: "/posters/desert-winds.jpg",
    backdrop: P(39260641),
    videoUrl: V + "BigBuckBunny.mp4",
    director: "نرگس آبیار",
    cast: ["فاطمه معتمدآریا", "حامد بهداد", "مهتاب کرامتی"],
    ageRating: "+13",
    quality: "4K",
    featured: true,
    trendingScore: 82,
    views: 890000,
  },
  {
    slug: "last-train",
    title: "آخرین قطار تهران",
    titleEn: "The Last Train",
    type: "movie",
    year: 2024,
    rating: 7.9,
    duration: 104,
    description:
      "یک مأمور امنیتی خسته، در آخرین قطار شبانه‌ی تهران، متوجه بمبی می‌شود که با سرعت قطار همگام شده است. اگر قطار بایستد، همه می‌میرند.",
    genres: ["اکشن", "هیجان‌انگیز"],
    poster: "/posters/last-train.jpg",
    backdrop: P(35171250),
    videoUrl: V + "ForBiggerEscapes.mp4",
    director: "محمدحسین مهدویان",
    cast: ["امیر جدیدی", "سحر دولتشاهی", "هوتن شکیبا"],
    ageRating: "+16",
    quality: "FHD",
    featured: false,
    trendingScore: 91,
    views: 1560000,
  },
  {
    slug: "city-shadows",
    title: "سایه‌های شهر",
    titleEn: "City Shadows",
    type: "movie",
    year: 2022,
    rating: 8.4,
    duration: 135,
    description:
      "کارآگاهی میان‌سال با پرونده‌ی قتلی روبه‌رو می‌شود که رد پایش به قدرتمندترین خانواده‌ی شهر می‌رسد. هرچه بیشتر می‌کاود، سایه‌ها بلندتر می‌شوند.",
    genres: ["جنایی", "درام", "نوآر"],
    poster: "/posters/city-shadows.jpg",
    backdrop: P(19943722),
    videoUrl: V + "ElephantsDream.mp4",
    director: "اصغر فرهادی",
    cast: ["پیمان معادی", "لیلا حاتمی", "علی مصفا"],
    ageRating: "+16",
    quality: "4K",
    featured: false,
    trendingScore: 76,
    views: 740000,
  },
  {
    slug: "the-deep",
    title: "اعماق",
    titleEn: "The Deep",
    type: "movie",
    year: 2025,
    rating: 7.6,
    duration: 98,
    description:
      "تیمی از غواصان تحقیقاتی در عمق سه هزار متری خلیج فارس، با چیزی مواجه می‌شوند که هرگز نباید بیدار می‌شد. اکسیژن تمام می‌شود و ترس تازه آغاز شده است.",
    genres: ["ترسناک", "هیجان‌انگیز", "علمی‌تخیلی"],
    poster: "/posters/the-deep.jpg",
    backdrop: P(932638),
    videoUrl: V + "ForBiggerMeltdowns.mp4",
    director: "شهرام مکری",
    cast: ["بهرام رادان", "پریناز ایزدیار", "مهران مدیری"],
    ageRating: "+18",
    quality: "4K",
    featured: false,
    trendingScore: 88,
    views: 1120000,
  },
  {
    slug: "summit",
    title: "قله",
    titleEn: "Summit",
    type: "movie",
    year: 2023,
    rating: 8.0,
    duration: 121,
    description:
      "دو برادر که سال‌هاست با هم حرف نزده‌اند، برای برآوردن آخرین آرزوی پدرشان تصمیم می‌گیرند در زمستان به قله‌ی دماوند صعود کنند. طوفان اما برنامه‌ی دیگری دارد.",
    genres: ["درام", "ماجراجویی"],
    poster: P(38887601),
    backdrop: P(38887601),
    videoUrl: V + "ForBiggerJoyrides.mp4",
    director: "رضا میرکریمی",
    cast: ["محسن تنابنده", "جواد عزتی", "الناز شاکردوست"],
    ageRating: "+13",
    quality: "FHD",
    featured: false,
    trendingScore: 64,
    views: 480000,
  },
  {
    slug: "pomegranate",
    title: "رنگ انار",
    titleEn: "Color of Pomegranate",
    type: "movie",
    year: 2024,
    rating: 8.5,
    duration: 109,
    description:
      "داستان عاشقانه‌ای در باغ‌های انار ساوه؛ دختری نقاش و پسری که هرگز رنگ‌ها را ندیده، در پاییزی که همه چیز را تغییر می‌دهد به هم می‌رسند.",
    genres: ["عاشقانه", "درام"],
    poster: P(30878453),
    backdrop: P(30878453),
    videoUrl: V + "ForBiggerFun.mp4",
    director: "سعید روستایی",
    cast: ["ترانه علیدوستی", "نوید محمدزاده"],
    ageRating: "+13",
    quality: "4K",
    featured: false,
    trendingScore: 79,
    views: 930000,
  },
  {
    slug: "red-winter",
    title: "زمستان سرخ",
    titleEn: "Red Winter",
    type: "movie",
    year: 2022,
    rating: 8.8,
    duration: 151,
    description:
      "روایتی تکان‌دهنده از سه سرباز جوان که در سخت‌ترین زمستان جنگ، در سنگری دورافتاده باید بین وظیفه و انسانیت انتخاب کنند.",
    genres: ["جنگی", "درام", "تاریخی"],
    poster: P(23384428),
    backdrop: P(23384428),
    videoUrl: V + "WeAreGoingOnBullrun.mp4",
    director: "ابراهیم حاتمی‌کیا",
    cast: ["هادی حجازی‌فر", "پژمان جمشیدی", "بهنوش طباطبایی"],
    ageRating: "+16",
    quality: "4K",
    featured: false,
    trendingScore: 71,
    views: 810000,
  },
  {
    slug: "night-shift",
    title: "شیفت شب",
    titleEn: "Night Shift",
    type: "movie",
    year: 2025,
    rating: 7.3,
    duration: 95,
    description:
      "کمدی سیاهی درباره‌ی نگهبان شبِ یک پارکینگ طبقاتی که ناخواسته وارد بزرگ‌ترین سرقت تاریخ شهر می‌شود و باید تا صبح زنده بماند.",
    genres: ["کمدی", "جنایی"],
    poster: P(8765934),
    backdrop: P(8765934),
    videoUrl: V + "ForBiggerBlazes.mp4",
    director: "سروش صحت",
    cast: ["رضا عطاران", "ژاله صامتی", "سیامک انصاری"],
    ageRating: "+13",
    quality: "FHD",
    featured: false,
    trendingScore: 69,
    views: 610000,
  },
  {
    slug: "fog-road",
    title: "جاده‌ی مه",
    titleEn: "Fog Road",
    type: "movie",
    year: 2023,
    rating: 7.1,
    duration: 101,
    description:
      "پنج مسافر غریبه در اتوبوسی شبانه گرفتار مهی می‌شوند که راه بازگشتی از آن نیست. هر توقف، یکی از آن‌ها را کم می‌کند.",
    genres: ["ترسناک", "معمایی"],
    poster: P(15707399),
    backdrop: P(15707399),
    videoUrl: V + "SubaruOutbackOnStreetAndDirt.mp4",
    director: "هومن سیدی",
    cast: ["نازنین بیاتی", "بابک کریمی", "مهرداد صدیقیان"],
    ageRating: "+16",
    quality: "FHD",
    featured: false,
    trendingScore: 58,
    views: 390000,
  },
  // ---------- SERIES ----------
  {
    slug: "house-seven",
    title: "خانه‌ی شماره هفت",
    titleEn: "House No. 7",
    type: "series",
    year: 2024,
    rating: 9.0,
    duration: 48,
    description:
      "دختری جوان عمارتی قدیمی را به ارث می‌برد که ۷۰ سال است کسی پا در آن نگذاشته. با هر دری که باز می‌کند، رازی از خانواده‌اش آشکار می‌شود که بهتر بود پنهان می‌ماند.",
    genres: ["معمایی", "درام", "ترسناک"],
    poster: "/posters/house-seven.jpg",
    backdrop: P(11850828),
    videoUrl: V + "ElephantsDream.mp4",
    director: "سعید نعمت‌الله",
    cast: ["پردیس احمدیه", "بهرام افشاری", "مریلا زارعی"],
    ageRating: "+16",
    quality: "4K",
    featured: true,
    trendingScore: 97,
    views: 3400000,
    eps: [
      { name: "کلید زنگ‌زده", synopsis: "سارا وارد عمارت می‌شود و اولین در بسته را پیدا می‌کند.", duration: 52 },
      { name: "اتاق آینه‌ها", synopsis: "تصویری در آینه که متعلق به سارا نیست.", duration: 47 },
      { name: "نامه‌های سوخته", synopsis: "بقایای نامه‌هایی در شومینه از سال ۱۳۳۲.", duration: 49 },
      { name: "صدای زیرزمین", synopsis: "هر شب ساعت سه، صدایی از زیرزمین می‌آید.", duration: 45 },
      { name: "مهمان ناخوانده", synopsis: "مردی ادعا می‌کند وارث اصلی خانه است.", duration: 50 },
      { name: "هفتمین در", synopsis: "دری که روی هیچ نقشه‌ای وجود ندارد.", duration: 58 },
    ],
  },
  {
    slug: "dark-capital",
    title: "پایتخت تاریک",
    titleEn: "Dark Capital",
    type: "series",
    year: 2025,
    rating: 8.9,
    duration: 55,
    description:
      "دادستان جوانی که می‌خواهد شبکه‌ی فساد را در بالاترین سطوح شهر افشا کند، درمی‌یابد که تنها متحدش، همان کسی است که باید محاکمه‌اش کند.",
    genres: ["جنایی", "درام", "هیجان‌انگیز"],
    poster: "/posters/dark-capital.jpg",
    backdrop: P(37911517),
    videoUrl: V + "TearsOfSteel.mp4",
    director: "همایون اسعدیان",
    cast: ["امین حیایی", "مهناز افشار", "فرهاد اصلانی"],
    ageRating: "+16",
    quality: "4K HDR",
    featured: true,
    trendingScore: 95,
    views: 2900000,
    eps: [
      { name: "پرونده‌ی صفر", synopsis: "اولین پرونده‌ی دادستان تازه‌وارد بوی خون می‌دهد.", duration: 56 },
      { name: "برج", synopsis: "قراردادی که هرگز امضا نشده بود.", duration: 54 },
      { name: "شاهد", synopsis: "تنها شاهد پرونده ناپدید می‌شود.", duration: 52 },
      { name: "معامله", synopsis: "پیشنهادی که نمی‌توان رد کرد.", duration: 57 },
      { name: "خیانت", synopsis: "دشمن نزدیک‌تر از آن چیزی است که فکرش را می‌کرد.", duration: 55 },
      { name: "دادگاه", synopsis: "روز محاکمه فرا می‌رسد.", duration: 61 },
      { name: "سقوط", synopsis: "پایان یک امپراتوری.", duration: 63 },
      { name: "سپیده", synopsis: "شهر بعد از طوفان.", duration: 59 },
    ],
  },
  {
    slug: "galaxy-migrants",
    title: "مهاجران کهکشان",
    titleEn: "Galaxy Migrants",
    type: "series",
    year: 2024,
    rating: 8.6,
    duration: 50,
    description:
      "دویست سال پس از ترک زمین، نسل سوم ساکنان سفینه‌ی «کاوه» به سیاره‌ی مقصد می‌رسند؛ اما آنچه پیدا می‌کنند، شبیه هیچ‌کدام از وعده‌ها نیست.",
    genres: ["علمی‌تخیلی", "ماجراجویی", "درام"],
    poster: "/posters/galaxy-migrants.jpg",
    backdrop: P(37269550),
    videoUrl: V + "Sintel.mp4",
    director: "کامبوزیا پرتوی",
    cast: ["ساره بیات", "حسین یاری", "پانته‌آ پناهی‌ها"],
    ageRating: "+13",
    quality: "4K",
    featured: false,
    trendingScore: 86,
    views: 1800000,
    eps: [
      { name: "بیداری", synopsis: "خواب سرد به پایان می‌رسد.", duration: 51 },
      { name: "دو ماه", synopsis: "اولین تصویر از سیاره‌ی نو.", duration: 48 },
      { name: "فرود", synopsis: "سفینه به مدار می‌رسد.", duration: 53 },
      { name: "سکوت سبز", synopsis: "جنگلی که نفس می‌کشد.", duration: 47 },
      { name: "سیگنال", synopsis: "پیامی از خودشان، از آینده.", duration: 55 },
      { name: "انتخاب", synopsis: "ماندن یا بازگشتن.", duration: 60 },
    ],
  },
  {
    slug: "dynasty",
    title: "دودمان",
    titleEn: "Dynasty",
    type: "series",
    year: 2023,
    rating: 9.2,
    duration: 60,
    description:
      "حماسه‌ای تاریخی از برآمدن و فروپاشی یک سلسله‌ی باستانی؛ جایی که برادر در برابر برادر می‌ایستد و تاج، سنگین‌تر از هر شمشیری است.",
    genres: ["تاریخی", "درام", "حماسی"],
    poster: "/posters/dynasty.jpg",
    backdrop: P(998635),
    videoUrl: V + "BigBuckBunny.mp4",
    director: "داوود میرباقری",
    cast: ["پارسا پیروزفر", "مهدی پاکدل", "ویشکا آسایش"],
    ageRating: "+13",
    quality: "4K HDR",
    featured: true,
    trendingScore: 93,
    views: 4100000,
    eps: [
      { name: "تاج‌گذاری", synopsis: "شاه جوان بر تخت می‌نشیند.", duration: 62 },
      { name: "توطئه", synopsis: "زمزمه‌هایی در راهروهای کاخ.", duration: 58 },
      { name: "نبرد دشت", synopsis: "اولین جنگ بزرگ.", duration: 65 },
      { name: "برادر", synopsis: "خون در برابر خون.", duration: 60 },
      { name: "شهبانو", synopsis: "قدرت پشت پرده.", duration: 57 },
      { name: "خیانت در تخت‌جمشید", synopsis: "شبی که همه چیز تغییر کرد.", duration: 63 },
      { name: "تبعید", synopsis: "شاه بدون تاج.", duration: 59 },
      { name: "بازگشت", synopsis: "قیام از خاکستر.", duration: 61 },
      { name: "فرجام", synopsis: "پایان دودمان.", duration: 70 },
    ],
  },
  {
    slug: "midnight-cafe",
    title: "کافه نیمه‌شب",
    titleEn: "Midnight Café",
    type: "series",
    year: 2025,
    rating: 8.3,
    duration: 35,
    description:
      "کافه‌ای کوچک که فقط از نیمه‌شب تا سپیده باز است و هر شب، آدمی با قصه‌ای تازه پشت پیشخوانش می‌نشیند. مجموعه‌ای آرام، انسانی و پر از طعم.",
    genres: ["درام", "کمدی", "عاشقانه"],
    poster: P(30878454),
    backdrop: P(30878454),
    videoUrl: V + "ForBiggerFun.mp4",
    director: "مانی حقیقی",
    cast: ["بهاره کیان‌افشار", "حامد کمیلی", "آتیلا پسیانی"],
    ageRating: "+13",
    quality: "FHD",
    featured: false,
    trendingScore: 74,
    views: 950000,
    eps: [
      { name: "قهوه‌ی ترک", synopsis: "مردی که هر شب یک صندلی خالی رزرو می‌کند.", duration: 34 },
      { name: "کیک هویج", synopsis: "دختری با چمدانی که هیچ‌وقت بازش نمی‌کند.", duration: 36 },
      { name: "چای دارچین", synopsis: "راننده‌ی تاکسی و آخرین مسافرش.", duration: 33 },
      { name: "شکلات داغ", synopsis: "دو غریبه و یک چتر.", duration: 37 },
      { name: "نعنا", synopsis: "شبی که کافه برق نداشت.", duration: 35 },
    ],
  },
];

const sampleReviews: Record<string, { author: string; rating: number; body: string }[]> = {
  "orbit-of-silence": [
    { author: "مهدی", rating: 10, body: "بهترین فیلم علمی‌تخیلی ایرانی که دیدم. جلوه‌های ویژه در حد هالیوود، صدا و موسیقی فوق‌العاده." },
    { author: "نگار", rating: 9, body: "نیم ساعت آخر نفسم بند اومده بود. حتماً روی صفحه بزرگ ببینید." },
  ],
  "endless-night": [
    { author: "آرش", rating: 9, body: "فضاسازی نوآر عالی. نورپردازی و فیلم‌برداری چشم‌نواز." },
  ],
  dynasty: [
    { author: "سارا", rating: 10, body: "قسمت آخر اشکم رو درآورد. بازی‌ها و طراحی صحنه بی‌نظیر." },
    { author: "کیان", rating: 9, body: "بهترین سریال تاریخی این سال‌ها." },
  ],
  "house-seven": [
    { author: "پریسا", rating: 9, body: "هر قسمت با کلیف‌هنگر تموم می‌شه، نمی‌شه دست ازش کشید!" },
  ],
};

let seeded = false;

export async function ensureSeeded() {
  if (seeded) return;
  const [{ count }] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(titles);
  if (Number(count) > 0) {
    seeded = true;
    return;
  }

  const thumbs = [P(35171250), P(6494958), P(3629669), P(39040884), P(6494957), P(34215537), P(19224452), P(34007217), P(23384407)];

  for (const t of seedTitles) {
    const { eps, ...row } = t;
    const [inserted] = await db.insert(titles).values(row).returning({ id: titles.id });
    if (eps?.length) {
      await db.insert(episodes).values(
        eps.map((e, i) => ({
          titleId: inserted.id,
          season: 1,
          number: i + 1,
          name: e.name,
          synopsis: e.synopsis,
          duration: e.duration,
          videoUrl: t.videoUrl,
          thumbnail: thumbs[i % thumbs.length],
        }))
      );
    }
    const revs = sampleReviews[t.slug];
    if (revs?.length) {
      await db.insert(reviews).values(revs.map((r) => ({ ...r, titleId: inserted.id })));
    }
  }
  seeded = true;
}
